version: "3"

services:
  mavp2p:
    image: ghcr.io/bellflight/vrc_mavp2p:latest
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/ttyTHS1:/dev/ttyTHS1

  mqtt:
    image: ghcr.io/bellflight/vrc_mqtt:latest
    ports:
      - "18830:18830"
    restart: on-failure

  fcc:
    depends_on:
      - mqtt
      - mavp2p
    image: ghcr.io/bellflight/vrc_fcc:latest
    network_mode: host
    restart: on-failure

  pcc:
    depends_on:
      - mqtt
    image: ghcr.io/bellflight/vrc_pcc:latest
    restart: on-failure
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  vio:
    depends_on:
      - mqtt
    image: ghcr.io/bellflight/vrc_vio:latest
    privileged: true
    restart: on-failure

  apriltag:
    depends_on:
      - mqtt
    build: apriltag
    restart: on-failure
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket

  fusion:
    depends_on:
      - mqtt
      - vio
      - apriltag
    image: ghcr.io/bellflight/vrc_fusion:latest
    restart: on-failure

  # sandbox:
  #   depends_on:
  #     - mqtt
  #   build: sandbox
  #   restart: on-failure
