version: "3"

services:
  mavp2p:
    build: mavp2p
    restart: unless-stopped
    network_mode: "host"
    devices:
      - /dev/ttyTHS1:/dev/ttyTHS1

  mqtt:
    build: mqtt
    ports:
      - "18830:18830"
    restart: on-failure

  fcm:
    depends_on:
      - mqtt
      - mavp2p
    build: fcm
    network_mode: "host"
    restart: on-failure

  vio:
    depends_on:
      - mqtt
    build: vio
    privileged: true
    restart: on-failure

  fusion:
    depends_on:
      - mqtt
      - vio
    build: fusion
    restart: on-failure
