name: Build Container MQTT

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/mqtt/**"
  push:
    branches:
      - main
    paths:
      - "VMC/mqtt/**"

jobs:
  check:
    uses: ./.github/workflows/templates/container.yml
    with:
      image: "mqtt"