name: Build PX4

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'PCC/GUI/'
  #     - 'VMC/GUI/'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Get latest release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy PCC library
        run: cp Libraries/pcc_library.py PCC/GUI/pcc_library.py

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Prepare Python
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install pyinstaller

      - name: Build PCC GUI
        run : |
          python -m pip install -r PCC/GUI/requirements.txt
          pyinstaller PCC/GUI/app.py --onefile --name VRCPCCTest --noconfirm

      - name: Build VMC GUI
        run : |
          python -m pip install -r VMC/GUI/requirements.txt
          pyinstaller VMC/GUI/app.py --onefile --name VRCControlGUI --add-data "VMC/GUI/img;img" --noconfirm

      - name: Upload GUIs to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.exe
          file_glob: true
          tag: ${{ steps.latest_release.release }}
          overwrite: true
