name: Build GUIs

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'PCC/GUI/'
  #     - 'VMC/GUI/'

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Get latest release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy libraries
        shell: bash
        run: |
          cp Libraries/pcc_library.py PCC/GUI/
          cp Libraries/qt_icon.py PCC/GUI/
          mkdir -p PCC/GUI/img
          cp -r Libraries/img PCC/GUI/img

          cp Libraries/qt_icon.py VMC/GUI/
          mkdir -p VMC/GUI/img
          cp -r Libraries/img VMC/GUI/img

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Prepare Python
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install pyinstaller

      - name: Build PCC GUI
        run: |
          python -m pip install -r PCC/GUI/requirements.txt
          pyinstaller PCC/GUI/app.py --onefile --name VRCPCCTest --icon Libraries/img/logo.ico --add-data "Libraries/img;img" --noconfirm

      - name: Build VMC GUI
        run: |
          python -m pip install -r VMC/GUI/requirements.txt
          pyinstaller VMC/GUI/app.py --onefile --name VRCControlGUI --icon Libraries/img/logo.ico --add-data "Libraries/img;img" --noconfirm

      - name: Upload GUIs to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.exe
          file_glob: true
          tag: ${{ steps.latest_release.outputs.tag_name }}
          overwrite: true
