name: Build PCC Firmware

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Apply patches
        run: git apply ../queue-default.patch
        working-directory: PCC/ControlSoftware/libraries/Queue

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install platformio --upgrade

      - name: Build firmware
        run: pio run --verbose
        working-directory: PCC/ControlSoftware

      # Firmware file is in PCC/ControlSoftware/.pio/build/adafruit_feather_m4/firmware.bin