name: Build PX4

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'PX4/'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Get latest release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PX4 firmware
        run: PX4/generate.sh --firmware

      - name: Upload firmware to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PX4/target/*.px4
          file_glob: true
          tag: ${{ steps.latest_release.outputs.tag_name }}
          overwrite: true
