name: Build PX4

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'PX4/'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Get latest release
        id: latest_release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      # this really isn't necessary, but we need to to make one local commit
      - name: Configure git
        run:
          git config --global user.email "github-bot@bellflight.com"
          git config --global user.name "Github Actions"

      - name: Build PX4 firmware
        shell: bash
        run: |
          chmod +x PX4/generate.sh
          PX4/generate.sh --firmware

      - name: Upload firmware to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PX4/target/*.px4
          file_glob: true
          tag: ${{ steps.latest_release.outputs.tag_name }}
          overwrite: true
