name: Build PX4

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'PX4/'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Get latest release
        id: latest_release
        uses: rez0n/actions-github-release@main
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          type: stable

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PX4 firmware
        run: PX4/generate.sh --firmware

      - name: Upload firmware to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PX4/target/*.px4
          file_glob: true
          tag: ${{ steps.latest_release.outputs.release }}
          overwrite: true
