name: Build PX4

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'PX4/'
  push:
    branches:
      - main
    paths:
      - 'PX4/'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Get latest release
        id: latest_release
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build PX4 firmware
        shell: bash
        run: python3 PX4/generate.py host --px4

      - name: Upload firmware to release
        if: github.event_name != 'pull_request'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PX4/target/*.px4
          file_glob: true
          tag: ${{ steps.latest_release.outputs.tag_name }}
          overwrite: true
