name: Python Checks VMC Status

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/status/**"
      - "Libraries/**"
      - "requirements-dev.txt"
      - "package-lock.json"

jobs:
  check:
    uses: ./.github/workflows/templates/python.yml
    with:
      project: "VMC/status"