name: Python Checks VMC Apriltag

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/apriltag/python/**"
      - "Libraries/**"
      - "requirements-dev.txt"
      - "package-lock.json"

jobs:
  check:
    uses: ./.github/workflows/python.yml
    with:
      project: "VMC/apriltag/python"