name: Python Formatting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Copy libraries
        run: python scripts/copy_libraries.py

      - name: Install Packages
        run: |
          npm install pyright
          python -m pip install pip wheel --upgrade
          python -m pip install -r requirements-dev.txt
          python ./scripts/dev_setup.py
          python ./scripts/copy_libraries.py

      - name: Check Formatting
        run: python -m black . --check

      - name: Check Import Order
        run: python -m isort --profile black . --check

      - name: Check Unused Imports
        run: python -m autoflake --recursive . --check

      - name: Check Type Hints
        run: python -m pyleft .

      - name: Check Typing
        run: npx pyright .