name: Python Checks Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**.py"
      - "requirements-dev.txt"
      - "package-lock.json"

jobs:
  check:
    uses: ./.github/workflows/templates/python.yml
    with:
      project: "docs"